### ISSUE TITLE
x_wu is not read in lis2du12_all_sources_get()

### ISSUE THREAD

**Issue by janewedingco** [STMicroelectronics/lis2du12-pid#2]
if (all_int_src.wu_ia_all == 1U || all_int_src.sleep_change_ia_all == 1U)
    {
      lis2du12_wake_up_src_t wu_src;

      ret = lis2du12_read_reg(ctx, LIS2DU12_WAKE_UP_SRC, (uint8_t*)&wu_src, 1);

      val->wake_up_z = wu_src.z_wu;
      val->wake_up_y = wu_src.y_wu;
      **val->wake_up_x = wu_src.z_wu;**    --> should be wu_src.x_wu

      val->sleep_state = wu_src.sleep_state;
    }

**Comment by avisconti** [comment]
fixed by 935e3a0
